package mimetypes

import (
	"fmt"
	"io"
	"strings"
	"text/template"
)

var rootTmpl = template.New("root")

var mimeTypesTmpl = template.Must(rootTmpl.New("mimeTypes").Parse(strings.TrimSpace(`
# THIS FILE IS AUTO-GENERATED by nginx-mimes-gen. DO NOT EDIT.

types {
    {{range .}}{{.Name }}{{range .Extensions}} {{.}}{{end}};
    {{end}}
}
`)))

func PrintConfiguration(out io.Writer, types []MimeType) error {
	if err := mimeTypesTmpl.Execute(out, types); err != nil {
		fmt.Fprintf(out, "\n\nerror: %+v\n\n", err)
		return err
	}
	fmt.Fprint(out, "\n")

	return nil
}
